# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile_test                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sarbaill <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/20 23:27:33 by sarbaill          #+#    #+#              #
#    Updated: 2018/11/22 22:23:35 by sarbaill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = ft_display_file.c

FLAG = -Wall -Wextra -Werror

all : $(NAME)

$(NAME) : 
	gcc $(FLAG) $(SRC) -o $(NAME)

clean : 
	rm -rf $(OBJ)

fclean :
	rm -rf $(NAME)

re : fclean all 
